export const user = [
  {
    userId: 1,
    fullname: "Ahmad Sidik",
    email: "ahmad@mail.com",
    password: "Admin123",
    gender: "Male",
    phone: "123123123123",
    address: "Kota Bogor",
    role: "user",
    img: "/img/profile.png",
  },
  {
    userId: 2,
    fullname: "Sidik Rudini",
    email: "sidik@mail.com",
    password: "Admin123",
    gender: "Male",
    phone: "08800880088",
    address: "Kota Bogor",
    role: "user",
    img: "",
  },
  {
    userId: 3,
    fullname: "Rudini",
    email: "rudini@mail.com",
    password: "Admin123",
    gender: "Male",
    phone: "08800880088",
    address: "Kota Bogor",
    role: "admin",
    img: "",
  },
];

export const trip = [
  {
    tripId: 1,
    title: "4D/3N Labuan Bajo Delight",
    price: 4900000,
    country: "Indonesia",
    quota: 15,
    pict: [
      "/img/card1.jpeg",
      "/img/card2.jpg",
      "/img/card3.jpg",
      "/img/card4.jpg",
      "/img/card2.jpg",
    ],
    info: {
      accomodation: "Five Star Hotels",
      transportation: "Garuda Indonesia",
      eat: "3x each day",
      duration: "2 Day 5 Night",
      date: "30 February 2023",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus molestie, magna vitae bibendum commodo, mauris leo rutrum sem, nec pellentesque nunc diam nec enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at sem eget neque faucibus sagittis eu ut justo. Sed lobortis ex aliquam elit dictum finibus. Vivamus condimentum neque sit amet massa sagittis pellentesque. Vestibulum ac neque eget nulla varius rhoncus. Suspendisse imperdiet quam sed rhoncus sodales. Duis arcu nisl, finibus id pulvinar a, dictum vel eros. Pellentesque eget efficitur ligula, in ultrices nisl. Sed tempus ipsum risus, quis scelerisque dui convallis eu. Donec eget lacus felis. Mauris odio ex, eleifend at lobortis vel, feugiat tempus velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla facilisi. Suspendisse ut arcu tristique, molestie diam sollicitudin, dapibus nisi. Phasellus condimentum semper urna nec laoreet.",
  },
  {
    tripId: 2,
    title: "3D2N MOROTAI TOUR PACKAGE D’ALOHA RESORT MOROTAI – MALUKU UTARA",
    price: 3500000,
    country: "Indonesia",
    quota: 15,
    pict: [
      "/img/card4.jpg",
      "/img/card1.jpeg",
      "/img/card2.jpg",
      "/img/card3.jpg",
    ],
    info: {
      accomodation: "Five Star Hotels",
      transportation: "Garuda Indonesia",
      eat: "3x each day",
      duration: "2 Day 5 Night",
      date: "12 January 2023",
    },
    desc: "Proin egestas dui non cursus aliquet. Vivamus feugiat tellus mi, ac sagittis magna pellentesque a. Sed lobortis efficitur accumsan. Integer faucibus odio id magna iaculis, ut tristique nulla ullamcorper. Vestibulum erat eros, sagittis vitae erat id, bibendum vehicula ipsum. Sed tincidunt, ipsum vitae aliquam condimentum, nisl urna finibus leo, sed tempus velit tortor sed justo. Aliquam eleifend dui urna, non luctus massa pretium a. Donec sodales, ex et venenatis eleifend, tellus lectus egestas massa, in finibus nulla nunc eget justo. Donec posuere massa ligula, quis aliquam turpis consequat quis. Etiam in dignissim risus. Quisque porta porttitor nibh ut lacinia. Curabitur id massa sollicitudin, dignissim metus vitae, imperdiet dolor. Cras non rutrum lorem. Quisque urna purus, pharetra eget libero ut, rhoncus tincidunt massa. Quisque facilisis nibh eu ex dapibus posuere. Duis luctus purus eget lobortis luctus.",
  },
  {
    tripId: 3,
    title: "6D/5N The Thrill of Mount Kenya",
    price: 10000000,
    country: "Kenya",
    quota: 15,
    pict: [
      "/img/card3.jpg",
      "/img/card4.jpg",
      "/img/card1.jpeg",
      "/img/card2.jpg",
      "/img/card4.jpg",
      "/img/card1.jpeg",
    ],
    info: {
      accomodation: "Five Star Hotels",
      transportation: "Garuda Indonesia",
      eat: "3x each day",
      duration: "2 Day 5 Night",
      date: "14 Maret 2023",
    },
    desc: "Integer lobortis velit risus, sed vulputate quam pretium a. Nullam pellentesque mauris nec sapien egestas, id lobortis magna aliquet. Cras id diam ut dui pharetra dictum. Donec a nisi ac quam lobortis tristique aliquam eget nunc. Nam fringilla, ante suscipit laoreet bibendum, justo enim placerat urna, ut interdum justo arcu id sem. Ut convallis erat nec iaculis pharetra. Nunc malesuada sed orci a iaculis. Suspendisse potenti. Sed et lectus erat. Phasellus luctus dui quis sem sollicitudin, luctus bibendum libero scelerisque. Vestibulum sed nisl tincidunt, bibendum mauris in, porta leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque metus arcu, facilisis tristique lectus vitae, semper auctor ipsum. Donec eu nibh arcu.",
  },
  {
    tripId: 4,
    title: "23D/22N Birding Kenya Style",
    price: 25000000,
    country: "Kenya",
    quota: 15,
    pict: [
      "/img/card2.jpg",
      "/img/card3.jpg",
      "/img/card4.jpg",
      "/img/card1.jpeg",
      "/img/card3.jpg",
      "/img/card4.jpg",
    ],
    info: {
      accomodation: "Five Star Hotels",
      transportation: "Garuda Indonesia",
      eat: "3x each day",
      duration: "2 Day 5 Night",
      date: "18 April 2023",
    },
    desc: "Aliquam urna lectus, pulvinar eu euismod a, auctor vitae ligula. Mauris eros nisl, ornare in convallis sit amet, vulputate at neque. Cras pharetra metus est, vitae tempus felis sagittis at. Sed metus purus, pellentesque nec interdum ut, molestie a arcu. In pulvinar ante neque, at ullamcorper eros vestibulum vitae. Nullam rhoncus gravida enim, et hendrerit mauris rutrum non. Fusce ac velit eu neque hendrerit pharetra. Quisque cursus lacinia nulla, vel tempor orci commodo ac. Integer ultricies at arcu ut congue. Nunc ultricies maximus enim convallis tempor.",
  },
  {
    tripId: 5,
    title: "4D/3N Dazzling Rift Valley",
    price: 8000000,
    country: "Kenya",
    quota: 15,
    pict: [
      "/img/card4.jpg",
      "/img/card2.jpg",
      "/img/card1.jpeg",
      "/img/card3.jpg",
      "/img/card2.jpg",
      "/img/card1.jpeg",
    ],
    info: {
      accomodation: "Five Star Hotels",
      transportation: "Garuda Indonesia",
      eat: "3x each day",
      duration: "2 Day 5 Night",
      date: "32 Mei 2023",
    },
    desc: "Aliquam urna lectus, pulvinar eu euismod a, auctor vitae ligula. Mauris eros nisl, ornare in convallis sit amet, vulputate at neque. Cras pharetra metus est, vitae tempus felis sagittis at. Sed metus purus, pellentesque nec interdum ut, molestie a arcu. In pulvinar ante neque, at ullamcorper eros vestibulum vitae. Nullam rhoncus gravida enim, et hendrerit mauris rutrum non. Fusce ac velit eu neque hendrerit pharetra. Quisque cursus lacinia nulla, vel tempor orci commodo ac. Integer ultricies at arcu ut congue. Nunc ultricies maximus enim convallis tempor.",
  },
  {
    tripId: 6,
    title: "2D/1N Universal Studio Singapore",
    price: 5000000,
    country: "Singapore",
    quota: 15,
    pict: [
      "/img/card1.jpeg",
      "/img/card4.jpg",
      "/img/card2.jpg",
      "/img/card1.jpeg",
      "/img/card3.jpg",
      "/img/card2.jpg",
    ],
    info: {
      accomodation: "Five Star Hotels",
      transportation: "Garuda Indonesia",
      eat: "3x each day",
      duration: "2 Day 5 Night",
      date: "9 February 2023",
    },
    desc: "Aliquam urna lectus, pulvinar eu euismod a, auctor vitae ligula. Mauris eros nisl, ornare in convallis sit amet, vulputate at neque. Cras pharetra metus est, vitae tempus felis sagittis at. Sed metus purus, pellentesque nec interdum ut, molestie a arcu. In pulvinar ante neque, at ullamcorper eros vestibulum vitae. Nullam rhoncus gravida enim, et hendrerit mauris rutrum non. Fusce ac velit eu neque hendrerit pharetra. Quisque cursus lacinia nulla, vel tempor orci commodo ac. Integer ultricies at arcu ut congue. Nunc ultricies maximus enim convallis tempor.",
  },
];

export const orderData = [
  {
    orderId: "trx00001",
    userId: 1,
    tripId: 1,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "new",
    qty: 2,
    totalPrice: 9800000,
    img: "",
  },
  {
    orderId: "trx00002",
    userId: 2,
    tripId: 1,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "new",
    qty: 1,
    totalPrice: 4900000,
    img: "",
  },
  {
    orderId: "trx00003",
    userId: 1,
    tripId: 2,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "new",
    qty: 1,
    totalPrice: 3500000,
    img: "",
  },
  {
    orderId: "trx00004",
    userId: 2,
    tripId: 2,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "new",
    qty: 1,
    totalPrice: 3500000,
    img: "",
  },
  {
    orderId: "trx00005",
    userId: 1,
    tripId: 5,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "pending",
    qty: 1,
    totalPrice: 8000000,
    img: "/img/receipt.png",
  },
  {
    orderId: "trx00006",
    userId: 2,
    tripId: 6,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "pending",
    qty: 1,
    totalPrice: 5000000,
    img: "/img/receipt.png",
  },
  {
    orderId: "trx00007",
    userId: 2,
    tripId: 5,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "approve",
    qty: 1,
    totalPrice: 8000000,
    img: "/img/receipt.png",
  },
  {
    orderId: "trx00008",
    userId: 1,
    tripId: 6,
    bookingDate: "Thursday, 15 Desember 2022",
    status: "approve",
    qty: 1,
    totalPrice: 5000000,
    img: "/img/receipt.png",
  },
];
